# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-27 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('api_doc_shared', models.BooleanField(default=False)),
                ('api_demo_given', models.BooleanField(default=False)),
                ('physical_meeting', models.BooleanField(default=False)),
                ('uat_release', models.BooleanField(default=False)),
                ('risk_parameters_asked_santosh', models.BooleanField(default=False)),
                ('risk_parameters_set_uat', models.BooleanField(default=False)),
                ('risk_parameters_verified', models.BooleanField(default=False)),
                ('contract_created_uat', models.BooleanField(default=False)),
                ('product_created_uat', models.BooleanField(default=False)),
                ('product_parameters_verified', models.BooleanField(default=False)),
                ('cohort_step_completed', models.BooleanField(default=False)),
                ('cohort_step_verified', models.BooleanField(default=False)),
                ('loan_step_completed', models.BooleanField(default=False)),
                ('loan_step_verified', models.BooleanField(default=False)),
                ('repayment_step_completed', models.BooleanField(default=False)),
                ('repayment_step_verified', models.BooleanField(default=False)),
                ('uat_loan_numbers_verified', models.BooleanField(default=False)),
                ('uat_demo_taken', models.BooleanField(default=False)),
                ('data_migrated', models.BooleanField(default=False)),
                ('contract_created_live', models.BooleanField(default=False)),
                ('product_created_live', models.BooleanField(default=False)),
                ('risk_parameters_set_live', models.BooleanField(default=False)),
                ('live_credentials_released', models.BooleanField(default=False)),
                ('screenshots_taken', models.BooleanField(default=False)),
                ('live_loan_tested', models.BooleanField(default=False)),
                ('marketing_call', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(blank=True, choices=[('cc', 'Create Cohort'), ('pq', 'Pre Qualifications'), ('cl', 'Create Loan'), ('ld', 'Loan Disbursal'), ('ldc', 'Loan Disbursal Confirmation'), ('pa', 'Payment Advice'), ('pu', 'Payment Upload')], max_length=10, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserHappyOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_on', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=15, null=True)),
                ('aadhaar_photo_front', models.ImageField(blank=True, null=True, upload_to=b'aadhaar_front/')),
                ('aadhaar_photo_back', models.ImageField(blank=True, null=True, upload_to=b'aadhaar_back/')),
                ('pan_number', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=b'profile/')),
                ('pancard_photo', models.ImageField(blank=True, null=True, upload_to=b'pancard/')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=5, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=15, null=True)),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
