# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-26 22:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zruser', '0032_auto_20180925_1606'),
        ('zrpayment', '0025_auto_20180925_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('loan_uid', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=30)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('disbursed_on', models.DateField()),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='happy_loan', to='zrpayment.PaymentRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zruser.ZrUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HappyOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cohort_uid', models.CharField(max_length=50)),
                ('kyc_status', models.CharField(max_length=15)),
                ('tenure', models.CharField(max_length=15)),
                ('pq_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('calculated_on', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zruser.ZrUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HappyRepayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('repayments_request_ref', models.CharField(max_length=50)),
                ('loan_uid', models.CharField(max_length=50)),
                ('amount_repaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=15)),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='happy_repayment', to='zrpayment.PaymentRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zruser.ZrUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(blank=True, choices=[('cc', 'Create Cohort'), ('pq', 'Pre Qualifications'), ('cl', 'Create Loan'), ('ld', 'Loan Disbursal'), ('ldc', 'Loan Disbursal Confirmation'), ('pa', 'Payment Advice'), ('pu', 'Payment Upload')], max_length=10, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zruser.ZrUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
