# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-21 13:28
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zruser', '0031_auto_20180726_2039'),
        ('zrpayment', '0024_auto_20180910_1815'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(blank=True, choices=[('cc', 'Create Cohort'), ('pq', 'Pre Qualifications'), ('cl', 'Create Loan'), ('ld', 'Loan Disbursal'), ('ldc', 'Loan Disbursal Confirmation'), ('pa', 'Payment Advice'), ('pu', 'Payment Upload')], max_length=10, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zruser.ZrUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserHappyLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('loan_uid', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=30)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('disbursed_on', models.DateField()),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='happyloan', to='zrpayment.PaymentRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zruser.ZrUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserHappyOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cohort_uid', models.CharField(max_length=50)),
                ('kyc_status', models.CharField(max_length=15)),
                ('tenure', models.CharField(max_length=15)),
                ('pq_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('calculated_on', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zruser.ZrUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserHappyRepayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('repayments_request_ref', models.CharField(max_length=50)),
                ('loan_uid', models.CharField(max_length=50)),
                ('amount_repaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zruser.ZrUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=15, null=True)),
                ('aadhaar_photo_front', models.CharField(blank=True, max_length=512)),
                ('aadhaar_photo_back', models.CharField(blank=True, max_length=512)),
                ('pan_number', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_photo', models.CharField(blank=True, max_length=512)),
                ('pan_card_photo', models.CharField(blank=True, max_length=512)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=5, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=15, null=True)),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('locality', models.CharField(blank=True, max_length=512, null=True)),
                ('street_address', models.CharField(blank=True, max_length=512, null=True)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='zruser.ZrUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
