# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-31 15:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('role_id', models.CharField(max_length=50)),
                ('role_user_id', models.CharField(max_length=50)),
                ('request_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('loan_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
