# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-23 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytransaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyTransaction',
        ),
    ]
