# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-02 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loanlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanlead',
            name='role_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
