# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-03 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20190102_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanlead',
            old_name='role_user_id',
            new_name='mobile_no',
        ),
    ]
