# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantPaymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('dmt_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('non_dmt_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('merchant_ref_no', models.CharField(blank=True, max_length=20, null=True)),
                ('distributor_ref_no', models.CharField(blank=True, max_length=20, null=True)),
                ('merchant_status', models.CharField(blank=True, choices=[(b'P', b'Pending'), (b'S', b'Success'), (b'F', b'Failure')], max_length=2, null=True)),
                ('distributor_status', models.CharField(blank=True, choices=[(b'P', b'Pending'), (b'S', b'Success'), (b'F', b'Failure')], max_length=2, null=True)),
                ('comments', models.TextField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'verbose_name_plural': 'PaymentRequests',
            },
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'PaymentModes',
            },
        ),
    ]
