# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zruser', '0001_initial'),
        ('zrpayment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpaymentrequest',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_payment_requests', to='zruser.ZrUser'),
        ),
        migrations.AddField(
            model_name='merchantpaymentrequest',
            name='distributor_payment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributor_requests', to='zrpayment.PaymentMode'),
        ),
        migrations.AddField(
            model_name='merchantpaymentrequest',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_payment_requests', to='zruser.ZrUser'),
        ),
        migrations.AddField(
            model_name='merchantpaymentrequest',
            name='merchant_payment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_requests', to='zrpayment.PaymentMode'),
        ),
    ]
