# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrpayment', '0002_auto_20170625_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantpaymentrequest',
            name='distributor_status',
        ),
        migrations.RemoveField(
            model_name='merchantpaymentrequest',
            name='merchant_status',
        ),
        migrations.AddField(
            model_name='merchantpaymentrequest',
            name='is_admin_approved',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='merchantpaymentrequest',
            name='is_distributor_approved',
            field=models.NullBooleanField(),
        ),
    ]
