# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zrpayment', '0003_auto_20170807_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantpaymentrequest',
            old_name='is_distributor_approved',
            new_name='is_supervisor_approved',
        ),
        migrations.RenameField(
            model_name='merchantpaymentrequest',
            old_name='distributor',
            new_name='supervisor',
        ),
    ]
