# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0020_zruser_residence_address'),
        ('zrpayment', '0004_auto_20170830_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('dmt_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('non_dmt_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('ref_no', models.CharField(blank=True, max_length=30, null=True)),
                ('challan_link', models.CharField(max_length=512)),
                ('is_approved', models.NullBooleanField()),
                ('comments', models.TextField(blank=True, max_length=1024, null=True)),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_request_mode', to='zrpayment.PaymentMode')),
                ('requester', models.ForeignKey(help_text='Who generates request of payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment_requester', to='zruser.ZrUser')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_request_supervisor', to='zruser.ZrUser')),
            ],
            options={
                'verbose_name_plural': 'PaymentRequests',
            },
        ),
    ]
