# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrpayment', '0005_paymentrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='challan_link',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='requester',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='supervisor',
            new_name='to_user',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='from_account_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='from_bank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Submitted'), (1, 'Approved'), (2, 'Rejected')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='to_account_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='to_bank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
