# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrpayment', '0006_auto_20171002_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
