# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zrpayment', '0007_paymentrequest_reject_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='amount',
        ),
    ]
