# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrpayment', '0008_remove_paymentrequest_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
