# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zrpayment', '0009_paymentrequest_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='from_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zruser.Bank'),
        ),
    ]
