# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrpayment', '0011_auto_20171005_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Submitted'), (1, 'Approved'), (2, 'Rejected'), (3, 'Refund')], default=0, null=True),
        ),
    ]
