# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrpayment', '0012_auto_20171007_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='from_account_no',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
