# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zrpayment', '0013_auto_20171007_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='from_bank',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zruser.Bank'),
            preserve_default=False,
        ),
    ]
