# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zrpayment', '0014_auto_20171007_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='to_account_no',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='to_bank',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='to_bank', to='zruser.Bank'),
            preserve_default=False,
        ),
    ]
