# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zrpayment', '0015_auto_20171007_1232'),
        ('zrpayment', '0012_auto_20171007_1226'),
    ]

    operations = [
    ]
