# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 19:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0024_auto_20171007_1108'),
        ('zrpayment', '0016_merge_20171007_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('txn_id', models.CharField(max_length=128)),
                ('vendor_txn_id', models.CharField(max_length=128)),
                ('customer', models.CharField(max_length=256)),
                ('transaction_request_json', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('transaction_response_json', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('additional_charges', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('is_settled', models.BooleanField(default=False)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zrpayment.PaymentMode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zruser.ZrUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='document',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
