# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zrtransaction', '0015_transaction_beneficiary_user'),
        ('zrpayment', '0017_auto_20171101_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Success'), ('F', 'Failure'), ('RP', 'Refund Pending'), ('R', 'Refunded'), ('E', 'Expired')], default='P', max_length=3),
        ),
        migrations.AddField(
            model_name='payments',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zrtransaction.Vendor'),
        ),
    ]
