# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0024_auto_20171007_1108'),
        ('zrpayment', '0018_auto_20171108_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_payments', to='zruser.ZrUser'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Success'), ('F', 'Failure'), ('RP', 'Refund Pending'), ('R', 'Refunded'), ('E', 'Expired'), ('SP', 'Spam')], default='P', max_length=3),
        ),
    ]
