# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-15 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zrpayment', '0019_auto_20171112_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='merchant',
        ),
    ]
