# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-11 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrpayment', '0020_remove_payments_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='payment_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Credit'), (1, 'Commission')], default=0, null=True),
        ),
    ]
