# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-10 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zrpayment', '0021_paymentrequest_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='type',
            new_name='payment_type',
        ),
    ]
