# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-29 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrpayment', '0021_paymentrequest_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Credit'), (1, 'Commission'), (2, 'Topup')], default=0, null=True),
        ),
    ]
