# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-10 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrpayment', '0022_auto_20180129_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Credit'), (1, 'Commission'), (2, 'Topup'), (3, 'Loan')], default=0, null=True),
        ),
    ]
