# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-10 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrpayment', '0023_auto_20180910_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='ref_no',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
