# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-25 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrpayment', '0024_auto_20180910_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Credit'), (1, 'Commission'), (2, 'Topup'), (3, 'Loan'), (4, 'LoanRepayment')], default=0, null=True),
        ),
    ]
