# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-17 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrpayment', '0025_auto_20180925_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='deposit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
