# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-15 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrpayment', '0027_paymentrequest_aeps_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='aeps_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
    ]
