# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZrCMSUserRole',
            new_name='UserRole',
        ),
        migrations.DeleteModel(
            name='ZrUserRole',
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name_plural': 'ZrUserRole'},
        ),
        migrations.AlterModelOptions(
            name='zradminuser',
            options={'verbose_name_plural': 'ZrAdminUser'},
        ),
    ]
