# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0002_auto_20170625_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpdetail',
            name='mobile_no',
            field=models.BigIntegerField(),
        ),
    ]
