# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0003_auto_20170629_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=64)),
                ('mobile_no', models.BigIntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'MerchantLead',
            },
        ),
    ]
