# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 03:47
from __future__ import unicode_literals

from django.db import migrations


def add_zrupee_distributor(apps, schema_editor):
    zuser_model = apps.get_model("zruser", "ZrUser")
    zr_admin_model = apps.get_model("zruser", "ZrAdminUser")
    django_user = apps.get_model("auth", "User")
    user_roles_model = apps.get_model("zruser", "UserRole")

    f_name = 'zuser'
    l_name = f_name
    dj_zuser = django_user.objects.create(
        username='zruser',
        email='zruser@zrupee.com',
        password='zruser',
        first_name=f_name,
        last_name=l_name
    )
    mobile_no = '9999999999'
    zuser_role = user_roles_model.objects.get(name='DISTRIBUTOR')
    zuser = zuser_model.objects.create(
        mobile_no=mobile_no,
        first_name=f_name,
        last_name=l_name,
        pass_word='zuser',
        email='zuser@zrupee.com',
        role=zuser_role,
        city='Ahmedabad',
        state='Gujarat',
        pincode=380007,
    )
    zr_admin_user = zr_admin_model.objects.create(
        mobile_no=mobile_no,
        zr_user=zuser,
        id=dj_zuser,
        role=user_roles_model.objects.filter(name='DISTRIBUTOR').last()
    )
    print("Created zr_admin_user(%s)" % (zr_admin_user))


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0005_zradminuser_zr_user'),
    ]

    operations = [
        migrations.RunPython(add_zrupee_distributor),
    ]
