# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0006_auto_20170809_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='zruser',
            name='pan_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
