# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0008_auto_20170813_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='zruser',
            name='gstin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
