# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0009_zruser_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdetail',
            name='document_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
