# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0010_auto_20170819_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdetail',
            name='document_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
