# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0011_auto_20170819_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdetail',
            name='by_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_kyc_details', to='zruser.ZrAdminUser'),
        ),
    ]
