# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0013_bankdetail_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='zruser',
            name='UPIID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
