# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0014_zruser_upiid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetail',
            name='account_type',
            field=models.CharField(choices=[('S', 'Savings Account'), ('C', 'Current Account')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zruser',
            name='business_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zruser',
            name='pan_no',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
