# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0014_zruser_upiid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zruser',
            name='business_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='zruser',
            name='pan_no',
            field=models.CharField(max_length=10),
        ),
    ]
