# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0015_auto_20170901_1206'),
        ('zruser', '0015_auto_20170901_1140'),
    ]

    operations = [
    ]
