# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0016_merge_20170901_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetail',
            name='channel',
            field=models.IntegerField(choices=[(0, b'ALL'), (1, b'NEFT'), (2, b'IMPS')], default=1),
        ),
    ]
