# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0017_bankdetail_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zruser',
            name='business_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='zruser',
            name='pan_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
