# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 20:00
from __future__ import unicode_literals

from django.db import migrations


def add_business_proof(apps, schema_editor):
    KycDetails = apps.get_model('zruser', 'KYCDocumentType')
    print(KycDetails.objects.create(
        name='Business Proof'
    ))


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0018_auto_20170902_1037'),
    ]

    operations = [
        migrations.RunPython(add_business_proof),
    ]
