# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0019_auto_20170907_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='zruser',
            name='residence_address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
