# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0020_zruser_residence_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=128)),
                ('bank_code', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'BankCodes',
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('mobile_no', models.BigIntegerField()),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=64, null=True)),
                ('gender', models.CharField(blank=True, choices=[(b'M', b'Male'), (b'F', b'Female'), (b'O', b'Others')], max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('state', models.CharField(blank=True, max_length=256, null=True)),
                ('pin_code', models.IntegerField(blank=True, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=512, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=512, null=True)),
                ('account_no', models.CharField(max_length=20)),
                ('account_type', models.CharField(choices=[(b'S', b'Savings Account'), (b'C', b'Current Account')], max_length=2)),
                ('channel', models.IntegerField(choices=[(0, b'ALL'), (1, b'NEFT'), (2, b'IMPS')], default=1)),
                ('IFSC_code', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=128)),
                ('bank_name', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_city', models.CharField(blank=True, max_length=256, null=True)),
                ('is_bank_account_verified', models.BooleanField(default=False)),
                ('is_user_active', models.BooleanField(default=True)),
                ('is_mobile_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Beneficiaries',
            },
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('mobile_no', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=64, null=True)),
                ('gender', models.CharField(blank=True, choices=[(b'M', b'Male'), (b'F', b'Female'), (b'O', b'Others')], max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('state', models.CharField(blank=True, max_length=256, null=True)),
                ('pin_code', models.IntegerField(blank=True, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=512, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=512, null=True)),
                ('is_user_active', models.BooleanField(default=True)),
                ('is_mobile_verified', models.BooleanField(default=False)),
                ('is_kyc_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Senders',
            },
        ),
        migrations.CreateModel(
            name='SenderKYCDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('document_id', models.CharField(blank=True, max_length=50, null=True)),
                ('document_link', models.CharField(max_length=512)),
                ('approval_status', models.CharField(choices=[(b'I', b'In Process'), (b'A', b'Approved'), (b'R', b'Rejected')], default=b'I', max_length=2)),
                ('by_approved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_sender_kyc_details', to='zruser.ZrAdminUser')),
                ('for_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_kyc_details', to='zruser.Sender')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_sender_kyc_details', to='zruser.KYCDocumentType')),
            ],
            options={
                'verbose_name_plural': 'SenderKYCDetail',
            },
        ),
    ]
