# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0021_bankcode_beneficiary_sender_senderkycdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankCode',
            new_name='Bank',
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name_plural': 'Banks'},
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries_from_bank', to='zruser.Bank'),
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='bank_city',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='bank_name',
        ),
        migrations.AlterUniqueTogether(
            name='beneficiary',
            unique_together=set([('account_no', 'bank')]),
        ),
    ]
