# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0022_auto_20170926_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='account_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bank',
            name='eko_bank_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='ifsc_formula',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bank',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='is_master_ifsc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries_from_bank', to='zruser.Bank'),
            preserve_default=False,
        ),
    ]
