# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 11:08
from __future__ import unicode_literals

from django.db import migrations


def create_admin_user(apps, schema_editor):
    DjangoUsr = apps.get_model('auth', 'User')
    UserRole = apps.get_model('zruser', 'UserRole')
    ZrUser = apps.get_model('zruser', 'ZrUser')
    ZrAdminUser = apps.get_model('zruser', 'ZrAdminUser')
    Wallet = apps.get_model('zrwallet', 'Wallet')

    dj_usr = DjangoUsr.objects.create(
        email='admin@zrupee.com',
        is_active=True,
        is_superuser=True,
        username='admin-user'
    )

    zr_usr = ZrUser.objects.create(
        mobile_no='9999999911',
        role=UserRole.objects.get(name='ADMINSTAFF'),
    )

    zr_admin_usr = ZrAdminUser.objects.create(
        id=dj_usr,
        mobile_no='9999999911',
        role=UserRole.objects.get(name='ADMINSTAFF'),
        zr_user=zr_usr
    )

    wallet = Wallet.objects.create(
        merchant=zr_usr
    )


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0023_auto_20170926_1928'),
    ]

    operations = [
        migrations.RunPython(create_admin_user),
    ]
