# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0024_auto_20171007_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinesssType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'BusinessTypes',
            },
        ),
    ]
