# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0025_businessstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='zruser',
            name='business_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_type', to='zruser.BusinesssType'),
        ),
    ]
