# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-13 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0026_zruser_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZrTerminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('mobile_no', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('pass_word', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=64, null=True)),
                ('gender', models.CharField(blank=True, choices=[(b'M', b'Male'), (b'F', b'Female'), (b'O', b'Others')], max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('state', models.CharField(blank=True, max_length=256, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=512, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=512, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_kyc_verified', models.BooleanField(default=False)),
                ('is_mobile_verified', models.BooleanField(default=False)),
                ('business_name', models.CharField(blank=True, max_length=256, null=True)),
                ('residence_address', models.CharField(blank=True, max_length=256, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True)),
                ('gstin', models.CharField(blank=True, max_length=20, null=True)),
                ('UPIID', models.CharField(blank=True, max_length=256, null=True)),
                ('business_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminal_business_type', to='zruser.BusinesssType')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zr_terminals', to='zruser.UserRole')),
            ],
            options={
                'verbose_name_plural': 'ZrTerminals',
            },
        ),
    ]
