# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-22 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0026_zruser_business_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpdetail',
            name='user',
        ),
        migrations.AddField(
            model_name='otpdetail',
            name='entityId',
            field=models.CharField(default='zruser_1', max_length=200),
        ),
    ]
