# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-27 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0027_auto_20180222_1105'),
        ('zruser', '0027_zrterminal'),
    ]

    operations = [
    ]
