# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-29 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0029_zruser_aadhaar_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='zruser',
            name='sales_agent',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
