# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-28 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0031_auto_20180726_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='ekyc_ref_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='zruser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zruser',
            name='ekyc_ref_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='zruser',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
