# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-08 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0032_auto_20180929_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='zruser',
            name='direct_distributor',
            field=models.NullBooleanField(default=None),
        ),
    ]
