# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-19 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0033_zruser_direct_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='zruser',
            name='user_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
