# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-01 19:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0034_zruser_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='zruser',
            name='misc',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
