# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-01 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0035_zruser_misc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zruser',
            name='misc',
        ),
        migrations.AddField(
            model_name='zruser',
            name='terms',
            field=models.BooleanField(default=False),
        ),
    ]
