TRANSACTION_STATUS_PENDING = 'P'
TRANSACTION_STATUS_SUCCESS = 'S'
TRANSACTION_STATUS_FAILURE = 'F'
TRANSACTION_STATUS_REFUND_PENDING = 'RP'
TRANSACTION_STATUS_REFUNDED = 'R'

TRANSACTION_STATUS = (
    (TRANSACTION_STATUS_PENDING, 'Pending'),
    (TRANSACTION_STATUS_SUCCESS, 'Success'),
    (TRANSACTION_STATUS_FAILURE, 'Failure'),
    (TRANSACTION_STATUS_REFUND_PENDING, 'Refund Pending'),
    (TRANSACTION_STATUS_REFUNDED, 'Refunded')
)

POLL_EXCLUDED_STATUS = [TRANSACTION_STATUS_SUCCESS, TRANSACTION_STATUS_FAILURE, TRANSACTION_STATUS_REFUNDED]

TX_STATUS_SUCCESS = 0
TX_STATUS_FAIL = 1
TX_STATUS_AWAITED = 2
TX_STATUS_REFUND_PENDING = 3
TX_STATUS_REFUNDED = 4

RECHARGES_TYPE = ['MOBILE_PREPAID', 'BROADBAND_PREPAID', 'DATACARD_PREPAID', 'DTH', 'TMW_CARD']

BILLS_TYPE = ['ELECTRICITY', 'GAS', 'LANDLINE', 'BROADBAND_POSTPAID', 'MOBILE_POSTPAID', 'DATACARD_POSTPAID']
