# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrtransaction', '0003_servicecircle_serviceprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sender',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='txn_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='beneficiary',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
