# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zrtransaction', '0004_auto_20170803_0635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='sender',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='merchant',
            new_name='user',
        ),
    ]
