# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zrtransaction', '0005_auto_20170819_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txn_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_list', to='zruser.ZrUser'),
        ),
    ]
