# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrtransaction', '0006_auto_20170819_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.CharField(max_length=256),
        ),
    ]
