# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrtransaction', '0007_auto_20170820_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='additional_charges',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
