# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrtransaction', '0008_transaction_additional_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_commission_created',
            field=models.BooleanField(default=False),
        ),
    ]
