# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zrtransaction', '0009_transaction_is_commission_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zrtransaction.ServiceProvider'),
        ),
    ]
