# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrtransaction', '0010_transaction_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('DMT', 'DMT'), ('BP', 'BillPayment')], default='BP', max_length=3),
            preserve_default=False,
        ),
    ]
