# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrtransaction', '0010_transaction_service_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[(b'P', b'Pending'), (b'S', b'Success'), (b'F', b'Failure'), (b'RP', b'Refund Pending'), (b'R', b'Refunded')], default=b'P', max_length=2),
        ),
    ]
