# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zrtransaction', '0011_auto_20170905_1759'),
        ('zrtransaction', '0011_transaction_source'),
    ]

    operations = [
    ]
