# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zrtransaction', '0012_merge_20170905_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='source',
        ),
    ]
