# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrtransaction', '0013_remove_transaction_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
