# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0021_bankcode_beneficiary_sender_senderkycdetail'),
        ('zrtransaction', '0014_auto_20170907_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='beneficiary_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zruser.Beneficiary'),
        ),
    ]
