# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-07 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0026_zruser_business_type'),
        ('zrtransaction', '0015_transaction_beneficiary_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorZruser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('is_attached_to_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_user_mappings', to='zruser.ZrUser')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vendor_mappings', to='zrtransaction.Vendor')),
            ],
            options={
                'verbose_name_plural': 'RetailerTerminalMappings',
            },
        ),
    ]
