# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-13 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0027_zrterminal'),
        ('zrtransaction', '0015_transaction_beneficiary_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorZrTerminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('vendor_user', models.CharField(max_length=256, null=True)),
                ('is_attached_to_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_vendor_mappings', to='zrtransaction.Vendor')),
                ('zr_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_terminal_mappings', to='zruser.ZrTerminal')),
            ],
            options={
                'verbose_name_plural': 'VendorZrTerminalMappings',
            },
        ),
        migrations.CreateModel(
            name='VendorZruser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('vendor_user', models.CharField(max_length=256, null=True)),
                ('is_attached_to_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vendor_mappings', to='zrtransaction.Vendor')),
                ('zr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_user_mappings', to='zruser.ZrUser')),
            ],
            options={
                'verbose_name_plural': 'VendorZruserMappings',
            },
        ),
    ]
