# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zruser', '0001_initial'),
        ('zrcommission', '0001_initial'),
        ('zrtransaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_commission', to='zruser.ZrUser'),
        ),
        migrations.AddField(
            model_name='commission',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributor_commission', to='zruser.ZrUser'),
        ),
        migrations.AddField(
            model_name='commission',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_commission', to='zruser.ZrUser'),
        ),
        migrations.AddField(
            model_name='commission',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zrtransaction.Transaction'),
        ),
    ]
