# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zrcommission', '0001_initial'),
        ('zrtransaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zrtransaction.Transaction'),
        ),
    ]
