# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0013_bankdetail_is_verified'),
        ('zrtransaction', '0007_auto_20170820_1052'),
        ('zrcommission', '0002_auto_20170625_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('distributor_percentage', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('merchant_percentage', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('zrupee_percentage', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_percentage', to='zruser.ZrUser')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zrtransaction.TransactionType')),
                ('transaction_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zrtransaction.Vendor')),
            ],
            options={
                'verbose_name_plural': 'CommissionPercentages',
            },
        ),
        migrations.RemoveField(
            model_name='commission',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='agent_commission',
        ),
        migrations.AlterField(
            model_name='commission',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='zrtransaction.Transaction'),
        ),
    ]
