# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0013_bankdetail_is_verified'),
        ('zrtransaction', '0007_auto_20170820_1052'),
        ('zrcommission', '0003_auto_20170821_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('commission_type', models.CharField(choices=[(b'F', b'Fixed Amount'), (b'P', b'Percentage')], max_length=2)),
                ('for_distributor', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('for_merchant', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('for_zrupee', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_structures', to='zruser.ZrUser')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zrtransaction.TransactionType')),
                ('transaction_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zrtransaction.Vendor')),
            ],
            options={
                'verbose_name_plural': 'CommissionStructures',
            },
        ),
        migrations.RemoveField(
            model_name='commissionpercentage',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='commissionpercentage',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='commissionpercentage',
            name='transaction_vendor',
        ),
        migrations.DeleteModel(
            name='CommissionPercentage',
        ),
    ]
