# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0013_bankdetail_is_verified'),
        ('zrtransaction', '0007_auto_20170820_1052'),
        ('zrcommission', '0004_auto_20170825_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillPayCommissionStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('commission_type', models.CharField(choices=[(b'F', b'Fixed Amount'), (b'P', b'Percentage')], max_length=2)),
                ('net_margin', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('commission_for_zrupee', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('commission_for_distributor', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('commission_for_sub_distributor', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('commission_for_merchant', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('tds_value', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('is_chargable', models.BooleanField(default=False)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_structures', to='zruser.ZrUser')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zrtransaction.ServiceProvider')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zrtransaction.TransactionType')),
                ('transaction_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zrtransaction.Vendor')),
            ],
            options={
                'verbose_name_plural': 'BillPayCommissionStructure',
            },
        ),
        migrations.CreateModel(
            name='DMTCommissionStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('commission_type', models.CharField(choices=[(b'F', b'Fixed Amount'), (b'P', b'Percentage')], max_length=2)),
                ('net_margin', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('commission_for_zrupee', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('commission_for_distributor', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('commission_for_sub_distributor', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('commission_for_merchant', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('tds_value', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('is_chargable', models.BooleanField(default=False)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmt_commission_structures', to='zruser.ZrUser')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zrtransaction.ServiceProvider')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zrtransaction.TransactionType')),
                ('transaction_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zrtransaction.Vendor')),
            ],
            options={
                'verbose_name_plural': 'DMTCommissionStructure',
            },
        ),
        migrations.RemoveField(
            model_name='commissionstructure',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='commissionstructure',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='commissionstructure',
            name='transaction_vendor',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='government_tax',
        ),
        migrations.AddField(
            model_name='commission',
            name='distributor_gst',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commission',
            name='distributor_tds',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commission',
            name='merchant_gst',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commission',
            name='merchant_tds',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commission',
            name='sub_distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_distributor_commissions', to='zruser.ZrUser'),
        ),
        migrations.AddField(
            model_name='commission',
            name='sub_distributor_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commission',
            name='sub_distributor_gst',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commission',
            name='sub_distributor_tds',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commission',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributor_commissions', to='zruser.ZrUser'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='distributor_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commission',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_commissions', to='zruser.ZrUser'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='merchant_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commission',
            name='zrupee_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='CommissionStructure',
        ),
    ]
