# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0005_auto_20170827_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmtcommissionstructure',
            name='gst_value',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=3),
        ),
    ]
