# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0014_zruser_upiid'),
        ('zrcommission', '0006_dmtcommissionstructure_gst_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='distributor_commission',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='distributor_gst',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='distributor_tds',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='merchant_commission',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='merchant_gst',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='merchant_tds',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='sub_distributor',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='sub_distributor_commission',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='sub_distributor_gst',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='sub_distributor_tds',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='zrupee_commission',
        ),
        migrations.AddField(
            model_name='commission',
            name='commission_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_commissions', to='zruser.ZrUser'),
        ),
        migrations.AddField(
            model_name='commission',
            name='net_commission',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commission',
            name='user_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commission',
            name='user_gst',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commission',
            name='user_tds',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
