# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0007_auto_20170827_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmtcommissionstructure',
            name='commission_type',
        ),
        migrations.RemoveField(
            model_name='dmtcommissionstructure',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='dmtcommissionstructure',
            name='is_chargable',
        ),
        migrations.RemoveField(
            model_name='dmtcommissionstructure',
            name='net_margin',
        ),
        migrations.RemoveField(
            model_name='dmtcommissionstructure',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='dmtcommissionstructure',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='dmtcommissionstructure',
            name='customer_fee',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=3),
        ),
    ]
