# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0008_auto_20170827_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billpaycommissionstructure',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='billpaycommissionstructure',
            name='transaction_vendor',
        ),
        migrations.AddField(
            model_name='billpaycommissionstructure',
            name='commission_unit',
            field=models.CharField(choices=[('P', 'Percentage'), ('R', 'Rupee')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billpaycommissionstructure',
            name='gst_value',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=3),
        ),
    ]
