# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0009_auto_20170831_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billpaycommissionstructure',
            name='commission_unit',
        ),
    ]
