# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0009_auto_20170831_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmtcommissionstructure',
            name='maximum_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='dmtcommissionstructure',
            name='min_charge',
            field=models.DecimalField(decimal_places=3, default=10.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='dmtcommissionstructure',
            name='minimum_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
    ]
