# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0013_auto_20170831_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpaycommissionstructure',
            name='commission_for_distributor',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='billpaycommissionstructure',
            name='commission_for_merchant',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='billpaycommissionstructure',
            name='commission_for_sub_distributor',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='billpaycommissionstructure',
            name='commission_for_zrupee',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
    ]
