# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0015_auto_20170831_1604'),
        ('zrcommission', '0011_auto_20170831_1612'),
    ]

    operations = [
    ]
