# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0016_merge_20170901_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpaycommissionstructure',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_commission_structure', to='zrtransaction.ServiceProvider'),
        ),
    ]
