# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0017_auto_20170901_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpaycommissionstructure',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
