# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0018_billpaycommissionstructure_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmtcommissionstructure',
            name='maximum_amount',
        ),
        migrations.RemoveField(
            model_name='dmtcommissionstructure',
            name='min_charge',
        ),
        migrations.RemoveField(
            model_name='dmtcommissionstructure',
            name='minimum_amount',
        ),
    ]
