# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 04:31
from __future__ import unicode_literals

from django.db import migrations


def add_dmt_comm_structure(apps, schema_editor):
    DMTCommissionStructure = apps.get_model('zrcommission', 'DMTCommissionStructure')
    Vendor = apps.get_model('zrtransaction', 'Vendor')
    dmt_structure = DMTCommissionStructure.objects.create(
        transaction_vendor=Vendor.objects.get(name='INSTANT_PAY'),
        customer_fee=1,
        commission_for_zrupee=25,
        commission_for_distributor=10,
        commission_for_sub_distributor=10,
        commission_for_merchant=55,
        tds_value=4.237,
        gst_value=15.2532,
        is_enabled=True,
        is_default=True,
        commission_type='P'
    )
    print(dmt_structure)


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0019_auto_20170905_0430'),
    ]

    operations = [
        migrations.RunPython(add_dmt_comm_structure),
    ]
