# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0020_auto_20170905_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='net_commission',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commission',
            name='user_gst',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commission',
            name='user_tds',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
