# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0021_auto_20170905_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpaycommissionstructure',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_structures', to='zruser.ZrUser'),
        ),
    ]
