# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0018_auto_20170902_1037'),
        ('zrtransaction', '0013_remove_transaction_source'),
        ('zrcommission', '0022_auto_20170905_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpaycommissionstructure',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dmtcommissionstructure',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dmt_commission_structures', to='zruser.ZrUser'),
        ),
        migrations.AddField(
            model_name='dmtcommissionstructure',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dmtcommissionstructure',
            name='maximum_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='dmtcommissionstructure',
            name='min_charge',
            field=models.DecimalField(decimal_places=3, default=10.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='dmtcommissionstructure',
            name='minimum_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
    ]
