# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0023_auto_20170907_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='bill_payment_comm_structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_pay_commissions', to='zrcommission.BillPayCommissionStructure'),
        ),
        migrations.AddField(
            model_name='commission',
            name='dmt_comm_structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dmt_commissions', to='zrcommission.DMTCommissionStructure'),
        ),
    ]
