# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0024_auto_20170907_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmtcommissionstructure',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
