# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0025_dmtcommissionstructure_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmtcommissionstructure',
            name='commission_type',
            field=models.CharField(choices=[(b'F', b'Fixed Amount'), (b'P', b'Percentage')], default='P', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billpaycommissionstructure',
            name='commission_for_distributor',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='billpaycommissionstructure',
            name='commission_for_merchant',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='billpaycommissionstructure',
            name='commission_for_sub_distributor',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='billpaycommissionstructure',
            name='commission_for_zrupee',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='billpaycommissionstructure',
            name='gst_value',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='billpaycommissionstructure',
            name='net_margin',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='billpaycommissionstructure',
            name='tds_value',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='commission',
            name='commission_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='all_commissions', to='zruser.ZrUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commission',
            name='net_commission',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commission',
            name='user_commission',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commission',
            name='user_gst',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commission',
            name='user_tds',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dmtcommissionstructure',
            name='commission_for_distributor',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='dmtcommissionstructure',
            name='commission_for_merchant',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='dmtcommissionstructure',
            name='commission_for_sub_distributor',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='dmtcommissionstructure',
            name='commission_for_zrupee',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='dmtcommissionstructure',
            name='customer_fee',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='dmtcommissionstructure',
            name='gst_value',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='dmtcommissionstructure',
            name='maximum_amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dmtcommissionstructure',
            name='min_charge',
            field=models.DecimalField(decimal_places=4, default=10.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='dmtcommissionstructure',
            name='minimum_amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dmtcommissionstructure',
            name='tds_value',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
    ]
