# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0026_auto_20170907_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='commission_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_commissions', to='zruser.ZrUser'),
        ),
    ]
