# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-10 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0027_auto_20170907_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpaycommissionstructure',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dmtcommissionstructure',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
    ]
