# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-10 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0028_auto_20180110_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billpaycommissionstructure',
            name='is_settled',
        ),
        migrations.RemoveField(
            model_name='dmtcommissionstructure',
            name='is_settled',
        ),
        migrations.AddField(
            model_name='commission',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
    ]
