# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-16 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0028_commission_is_settled'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmtcommissionstructure',
            name='sender_kyc_benefit',
            field=models.BooleanField(default=False),
        ),
    ]
