# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-05 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zrtransaction', '0017_auto_20180215_1024'),
        ('zrcommission', '0029_dmtcommissionstructure_sender_kyc_benefit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AEPSCommissionStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('commission_set', models.IntegerField()),
                ('commission_type', models.CharField(choices=[(b'F', b'Fixed Amount'), (b'P', b'Percentage')], max_length=2)),
                ('min_charge', models.DecimalField(decimal_places=4, default=10.0, max_digits=7)),
                ('minimum_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('maximum_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=9)),
                ('customer_fee', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('commission_for_zrupee', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('commission_for_distributor', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('commission_for_sub_distributor', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('commission_for_merchant', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('tds_value', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('gst_value', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('sender_kyc_benefit', models.BooleanField(default=False)),
                ('transaction_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zrtransaction.Vendor')),
            ],
            options={
                'verbose_name_plural': 'DMTCommissionStructure',
            },
        ),
    ]
