# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-06 08:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0030_aepscommissionstructure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aepscommissionstructure',
            name='commission_for_distributor',
        ),
        migrations.RemoveField(
            model_name='aepscommissionstructure',
            name='commission_for_merchant',
        ),
        migrations.RemoveField(
            model_name='aepscommissionstructure',
            name='commission_for_sub_distributor',
        ),
        migrations.RemoveField(
            model_name='aepscommissionstructure',
            name='commission_for_zrupee',
        ),
        migrations.RemoveField(
            model_name='aepscommissionstructure',
            name='commission_set',
        ),
        migrations.RemoveField(
            model_name='aepscommissionstructure',
            name='commission_type',
        ),
        migrations.RemoveField(
            model_name='aepscommissionstructure',
            name='customer_fee',
        ),
        migrations.RemoveField(
            model_name='aepscommissionstructure',
            name='gst_value',
        ),
        migrations.RemoveField(
            model_name='aepscommissionstructure',
            name='maximum_amount',
        ),
        migrations.RemoveField(
            model_name='aepscommissionstructure',
            name='min_charge',
        ),
        migrations.RemoveField(
            model_name='aepscommissionstructure',
            name='minimum_amount',
        ),
        migrations.RemoveField(
            model_name='aepscommissionstructure',
            name='sender_kyc_benefit',
        ),
        migrations.RemoveField(
            model_name='aepscommissionstructure',
            name='tds_value',
        ),
        migrations.AddField(
            model_name='aepscommissionstructure',
            name='rule',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
