# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-26 06:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zrtransaction', '0017_auto_20180215_1024'),
        ('zrcommission', '0030_aepscommissionstructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCommissionStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('rule', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('transaction_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zrtransaction.Vendor')),
            ],
            options={
                'verbose_name_plural': 'InsuranceCommissionStructure',
            },
        ),
    ]
