# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-22 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0030_aepscommissionstructure'),
        ('zrcommission', '0029_dmtcommissionstructure_sender_fee_limit'),
    ]

    operations = [
    ]
