# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-11 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0031_insurancecommissionstructure'),
        ('zrcommission', '0031_merge_20190722_1416'),
    ]

    operations = [
    ]
