# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-09-06 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zrcommission', '0032_merge_20190812_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmtcommissionstructure',
            name='sender_fee_limit',
        ),
    ]
