# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zruser', '0001_initial'),
        ('zrmapping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderbeneficiary',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_mapping', to='zruser.ZrUser'),
        ),
        migrations.AddField(
            model_name='senderbeneficiary',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_mappings', to='zruser.ZrUser'),
        ),
        migrations.AddField(
            model_name='merchantsender',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_mappings', to='zruser.ZrUser'),
        ),
        migrations.AddField(
            model_name='merchantsender',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_mappings', to='zruser.ZrUser'),
        ),
        migrations.AddField(
            model_name='merchantbeneficiary',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_mapping', to='zruser.ZrUser'),
        ),
        migrations.AddField(
            model_name='merchantbeneficiary',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_mapping', to='zruser.ZrUser'),
        ),
        migrations.AddField(
            model_name='distributormerchant',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_merchant_mappings', to='zruser.ZrUser'),
        ),
        migrations.AddField(
            model_name='distributormerchant',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_mappings', to='zruser.ZrUser'),
        ),
    ]
