# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrmapping', '0002_auto_20170625_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributormerchant',
            name='is_attaches_to_admin',
            field=models.BooleanField(default=False),
        ),
    ]
