# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrmapping', '0003_distributormerchant_is_attaches_to_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderbeneficiary',
            name='eko_beneficiary_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='senderbeneficiary',
            name='eko_sender_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
