# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0013_bankdetail_is_verified'),
        ('zrmapping', '0004_auto_20170820_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorSubDistributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('is_attached_to_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_dist_dist_mappings', to='zruser.ZrUser')),
                ('sub_distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dist_sub_dist_mappings', to='zruser.ZrUser')),
            ],
            options={
                'verbose_name_plural': 'DistributorSubDistributorMappings',
            },
        ),
        migrations.CreateModel(
            name='SubDistributorMerchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('is_attached_to_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_distributor_mappings', to='zruser.ZrUser')),
                ('sub_distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_sub_mappings', to='zruser.ZrUser')),
            ],
            options={
                'verbose_name_plural': 'SubDistributorMerchantMappings',
            },
        ),
        migrations.RenameField(
            model_name='distributormerchant',
            old_name='is_attaches_to_admin',
            new_name='is_attached_to_admin',
        ),
    ]
