# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0021_bankcode_beneficiary_sender_senderkycdetail'),
        ('zrmapping', '0005_auto_20170825_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderBeneficiaryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('eko_sender_id', models.CharField(blank=True, max_length=255, null=True)),
                ('eko_beneficiary_id', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_beneficiary_sender_mappings', to='zruser.Beneficiary')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_sender_beneficiary_mappings', to='zruser.Sender')),
            ],
            options={
                'verbose_name_plural': 'SenderBeneficiaryMapping',
            },
        ),
        migrations.AlterModelOptions(
            name='senderbeneficiary',
            options={'verbose_name_plural': 'SenderBeneficiary'},
        ),
    ]
