# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-26 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zrmapping', '0009_insurancecommission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecommission',
            name='insurance_commission_structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ins_comm_mappings', to='zrcommission.InsuranceCommissionStructure'),
        ),
    ]
