# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-22 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zrmapping', '0009_userbeneficiary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbeneficiary',
            old_name='merchant',
            new_name='user',
        ),
    ]
