# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-11 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zrmapping', '0010_auto_20190726_1240'),
        ('zrmapping', '0010_auto_20190722_1413'),
    ]

    operations = [
    ]
