# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zrwallet', '0002_auto_20170806_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('dmt_final_balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('dmt_initial_balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('non_dmt_initial_balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('non_dmt_final_balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('is_success', models.BooleanField(default=False)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='zrwallet.Wallet')),
            ],
            options={
                'verbose_name_plural': 'Wallets',
            },
        ),
    ]
