# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zrtransaction', '0012_merge_20170905_1806'),
        ('zrwallet', '0004_auto_20170827_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactions',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs', to='zrtransaction.Transaction'),
            preserve_default=False,
        ),
    ]
