# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zrwallet', '0005_wallettransactions_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactions',
            name='log_type',
            field=models.CharField(choices=[('transaction', 'Transaction'), ('balance', 'Balance')], default='transaction', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransactions',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs', to='zrtransaction.Transaction'),
        ),
    ]
