# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zrpayment', '0011_auto_20171005_1636'),
        ('zrwallet', '0006_auto_20171007_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactions',
            name='payment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zrpayment.PaymentRequest'),
        ),
        migrations.AlterField(
            model_name='wallettransactions',
            name='log_type',
            field=models.CharField(choices=[('transaction', 'Transaction'), ('balance', 'Balance'), ('refund', 'Refund')], default='transaction', max_length=20),
        ),
    ]
