# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrwallet', '0007_auto_20171007_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransactions',
            name='log_type',
            field=models.CharField(choices=[('transaction', 'Transaction'), ('balance', 'Balance'), ('refund_decrement', 'Refund'), ('refund_increment', 'Refund increment')], default='transaction', max_length=20),
        ),
    ]
