# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrwallet', '0007_auto_20171007_0602'),
    ]

    operations = [
    ]
