# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zrwallet', '0008_auto_20171007_1226'),
        ('zrwallet', '0009_remove_wallettransactions_log_type'),
    ]

    operations = [
    ]
