# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zruser', '0024_auto_20171007_1108'),
        ('zrwallet', '0010_merge_20171007_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_modified', models.DateTimeField(auto_now=True)),
                ('dmt_opening_balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('dmt_opening_wallet_balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('dmt_wallet_credit', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('dmt_wallet_debit', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('dmt_closing_balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('dmt_closing_wallet_balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('non_dmt_opening_balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('non_dmt_opening_wallet_balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('non_dmt_wallet_credit', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('non_dmt_wallet_debit', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('non_dmt_closing_balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('non_dmt_closing_wallet_balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zruser.ZrUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
