# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-01 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrwallet', '0011_passbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactions',
            name='dmt_closing_balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='non_dmt_closing_balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
