# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-13 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrwallet', '0012_auto_20180201_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='dmt_limit',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
    ]
