# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-17 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrwallet', '0014_wallettransactions_zr_dmt_closing_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransactions',
            name='zr_dmt_closing_balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
    ]
