# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-12 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrwallet', '0015_auto_20190117_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='aeps',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
