# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-13 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrwallet', '0016_wallet_aeps'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactions',
            name='aeps_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='aeps_closing_balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
