# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-13 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zrwallet', '0017_auto_20190613_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='aeps',
            new_name='aeps_amount',
        ),
    ]
