# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-15 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrwallet', '0018_auto_20190613_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='aeps_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransactions',
            name='aeps_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransactions',
            name='aeps_closing_balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
    ]
